apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-application
  template:
    metadata:
      labels:
        app: devops-application
    spec:
      containers:
      - name: devops-application
        image: erdincekzts/devops-application:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-application-service
spec:
  selector:
    app: devops-application
  ports:
  - port: 9090 # Service dinleyeceği Port
    targetPort: 8080 # Pod içindeki Container'ın Portu
  type: NodePort # Service tipi (ClusterIP, NodePort, LoadBalancer)     
  